---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-microvm-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if and .Values.serviceAccount.irsaRoleArn (ne .Values.serviceAccount.irsaRoleArn "") }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn | quote }}
  {{- end }}
