{{- if .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kube-microvm-operator.fullname" . }}-webhook-cert
  labels:
    {{- include "kube-microvm-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kube-microvm-operator.fullname" . }}-webhook-tls
  dnsNames:
    - {{ include "kube-microvm-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "kube-microvm-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ default "selfsigned-issuer" .Values.webhook.certManager.issuerRef.name }}
    kind: {{ default "ClusterIssuer" .Values.webhook.certManager.issuerRef.kind }}
  duration: 8760h
  renewBefore: 720h
{{- end }}
