apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microvm-admin
  labels:
    {{- include "kube-microvm-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["lambda.aws.amazon.com"]
    resources: ["microvms", "microvmpools", "microvmtemplates", "microvmnetworks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["lambda.aws.amazon.com"]
    resources: ["microvms/status", "microvmpools/status"]
    verbs: ["get"]
