{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-microvm-operator.fullname" . }}
  labels:
    {{- include "kube-microvm-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-microvm-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /q/metrics
      interval: 30s
{{- end }}
