apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kube-microvm-operator.fullname" . }}-validating
  labels:
    {{- include "kube-microvm-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kube-microvm-operator.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: validate.microvms.lambda.aws.amazon.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "kube-microvm-operator.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-microvm
        port: 443
    rules:
      - apiGroups: ["lambda.aws.amazon.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["microvms"]
